package com.example.imagurtask.models

import com.google.gson.annotations.SerializedName

data class GalleryData(
    @SerializedName("id") val id: String,
    @SerializedName("title") val title: String,
    @SerializedName("datetime") val datetime: Int,
    @SerializedName("cover") val cover: String,
    @SerializedName("cover_width") val coverWidth: Int,
    @SerializedName("cover_height") val coverHeight: Int,
    @SerializedName("account_url") val accountUrl: String,
    @SerializedName("account_id") val accountId: Int,
    @SerializedName("privacy") val privacy: String,
    @SerializedName("layout") val layout: String,
    @SerializedName("views") val views: Int,
    @SerializedName("link") val link: String,
    @SerializedName("ups") val ups: Int,
    @SerializedName("downs") val downs: Int,
    @SerializedName("points") val points: Int,
    @SerializedName("score") val score: Int,
    @SerializedName("is_album") val isAlbum: Boolean,
    @SerializedName("favorite") val favorite: Boolean,
    @SerializedName("nsfw") val nsfw: Boolean,
    @SerializedName("section") val section: String,
    @SerializedName("comment_count") val commentCount: Int,
    @SerializedName("favorite_count") val favoriteCount: Int,
    @SerializedName("topic") val topic: String,
    @SerializedName("topic_id") val topicId: Int,
    @SerializedName("images_count") val imagesCount: Int,
    @SerializedName("in_gallery") val inGallery: Boolean,
    @SerializedName("is_ad") val isAd: Boolean,
    @SerializedName("tags") val tags: List<Any>,
    @SerializedName("ad_type") val adType: Int,
    @SerializedName("ad_url") val adUrl: String,
    @SerializedName("in_most_viral") val inMostViral: Boolean,
    @SerializedName("include_album_ads") val includeAlbumAds: Boolean,
    @SerializedName("images") val images: List<Image>,
    @SerializedName("ad_config") val adConfig: AdConfig,
    @SerializedName("type") val type: String,
    @SerializedName("animated") val animated: Boolean,
    @SerializedName("width") val width: Int,
    @SerializedName("height") val height: Int,
    @SerializedName("size") val size: Int,
    @SerializedName("bandwidth") val bandwidth: Long,
    @SerializedName("has_sound") val hasSound: Boolean,
    @SerializedName("edited") val edited: Int,
    @SerializedName("mp4_size") val mp4Size: Int,
    @SerializedName("mp4") val mp4: String,
    @SerializedName("gifv") val gifv: String,
    @SerializedName("hls") val hls: String,
    @SerializedName("processing") val processing: Processing,
    @SerializedName("looping") val looping: Boolean,
    @SerializedName("description") val description: String?,
    @SerializedName("vote") val vote: Any?
)